### PR TITLE
Want to take over

### PR DESCRIPTION
**Pull request by levrik**
Hey there.
Sadly issues are disabled on this repo and I didn't find any contact info in your profile, so I'm trying to contact you this way.

First, thanks for making my package compatible with Preact. I see that you've stopped keeping this project updated after making the changes for Preact. I would like to take over this project and wanted to ask if you could give me access to the `mdi-preact` package on NPM for me to publish.

Thanks in advance 🙂

### CODE REVIEW

**Comment by GusRuss89** [comment]
Hi @levrik 

I've added you as a collaborator on npm. I'm not sure if you need anything else but let me know if you do.

I assume you'll just fork this repo to your own, then update npm to point to your version?

Thanks,
Angus

**Comment by levrik** [comment]
Hey, thanks for giving me access.
I planned to update the `generate.js` script to be able to create both packages.
I will credit you for the initial work of course 🙂

**Comment by levrik** [comment]
I just released an updated version of `mdi-preact`. Would be nice if you could merge this PR to redirect people to the correct repository.

**Comment by levrik** [comment]
Thanks!

**Pull request merged**
